/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reports.monthlyProfit;

import DatabaseConnection.OracleConn;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import static treainigcenter.MDIHome.REPORTSPATH;

/**
 *
 * @author David Sherif
 */
public class month extends javax.swing.JPanel {

    /**
     * Creates new form month
     */
    public month() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        info.clearthought.layout.TableLayout _tableLayoutInstance;

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        _tableLayoutInstance = new info.clearthought.layout.TableLayout();
        _tableLayoutInstance.setHGap(7);
        _tableLayoutInstance.setVGap(10);
        _tableLayoutInstance.setColumn(new double[]{170,120});
        _tableLayoutInstance.setRow(new double[]{info.clearthought.layout.TableLayout.MINIMUM,info.clearthought.layout.TableLayout.MINIMUM});
        setLayout(_tableLayoutInstance);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January - 1", "February - 2", "March - 3", "April - 4", "May - 5", "June - 6", "July - 7", "August - 8", "September - 9", "October - 10", "November - 11", "December - 12" }));
        add(jComboBox1, new info.clearthought.layout.TableLayoutConstraints(0, 0, 0, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jComboBox2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        add(jComboBox2, new info.clearthought.layout.TableLayoutConstraints(1, 0, 1, 0, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new info.clearthought.layout.TableLayoutConstraints(1, 1, 1, 1, info.clearthought.layout.TableLayout.FULL, info.clearthought.layout.TableLayout.FULL));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jComboBox2AncestorAdded
        jComboBox2.addItem(new GregorianCalendar().get(Calendar.YEAR)-1+"");
        for (int i = 0; i < 2; i++) {
            jComboBox2.addItem(new GregorianCalendar().get(Calendar.YEAR)+i+"");
        }
    }//GEN-LAST:event_jComboBox2AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        String s1=OracleConn.ret_value("select sum(c.courseprice*comvalue)/100 " +
"from payroll p JOIN COURSES c on C.COURSEID=P.COURSEID\n" +
"JOIN comissions j on j.tableid=P.PCT\n" +
"JOIN students f3 on F3.STDID=P.STDID where P.PAYDATE between TO_DATE('1-"+jComboBox1.getSelectedItem().toString().substring(0,3)+"-"+jComboBox2.getSelectedItem()+"','DD-MON-YYYY') and last_day('1-"+jComboBox1.getSelectedItem().toString().substring(0,3)+"-"+jComboBox2.getSelectedItem()+"')").toString(),

                s2=OracleConn.ret_value("select sum(employeesalary) from employees").toString();

        
        showREPORT(REPORTSPATH+"\\Reports\\monthlyProfit\\profits.jasper", 
            new Object[]{"p","1-"+jComboBox1.getSelectedItem().toString().substring(0,3)+"-"+jComboBox2.getSelectedItem(),
            "Income",s1,
            "deduction",s2,
            "profit",(Float.parseFloat(s1)-Float.parseFloat(s2))+"" });
        
        }catch(java.lang.NullPointerException y){JOptionPane.showMessageDialog(null, "No Transaction During This Period","Warning",JOptionPane.WARNING_MESSAGE);}
        
        this.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    // End of variables declaration//GEN-END:variables

 private void showREPORT(String PathJasper, Object[] Parameter) {

        try {
            Map params = null;

            // JasperCompileManager.compileReportToFile(jrxmlFileName, jasperFileName);
            if (Parameter == null) {
                params = null;
            } else {
                params = new HashMap();
                for (int i = 0; i < Parameter.length; i++) {
                    params.put(Parameter[i], Parameter[++i]);
                }
            }

            // Generate jasper printPathJasper.getFile().replaceAll("%20", " ")
            JasperPrint jprint = (JasperPrint) JasperFillManager.fillReport(PathJasper,
                    params,
                    OracleConn.GetConn());
          
            
            JasperViewer.viewReport(jprint, false,Locale.US);

            // Export pdf file
            //    JasperExportManager.exportReportToPdfFile(jprint, getClass().getResource("/Reports/Report.pdf").getFile().replaceAll("%20", " "));
//if(JOptionPane.showConfirmDialog(jDesktopPane1, "Do You Want To Open Report With PDF Reader ?")==JOptionPane.YES_OPTION)
            //     Desktop.getDesktop().open(new java.io.File(getClass().getResource("/Reports/Report.pdf").getFile().replaceAll("%20", " ")));
// JasperPrint jasperPrint = JasperFillManager.fillReport(PathJasper,params, OracleConn.OpenConn( ));
            //JasperExportManager.exportReportToPdfFile(jasperPrint, "A:\\My programs\\ad.pdf");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.print("Exceptiion" + e);
        }
    }


}
